# Generated by Django 4.2.5 on 2023-09-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('assigment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('professor_id', models.IntegerField()),
                ('stand_number', models.IntegerField()),
            ],
        ),
    ]
