# Generated by Django 4.2.5 on 2023-09-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rf', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='professor_id',
        ),
        migrations.AlterField(
            model_name='paper',
            name='stand_number',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='professors',
            field=models.ManyToManyField(to='app.professor'),
        ),
    ]
