# Generated by Django 4.2.5 on 2023-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_professor_remove_paper_professor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='assigment_id',
            new_name='paper_id',
        ),
    ]
