# Generated by Django 4.2.5 on 2023-10-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paper',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
