# Generated by Django 4.2.5 on 2023-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delivery_project_task_user_remove_student_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qualification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
