# Generated by Django 4.2.5 on 2023-10-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='content',
            field=models.JSONField(),
        ),
    ]
