# Generated by Django 4.2.5 on 2024-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_delivery_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='professors',
        ),
        migrations.AddField(
            model_name='project',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='advisors', to='app.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='responsibles', to='app.user'),
        ),
    ]
