name: Django CD

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - deploy-eureka

jobs:
  DeployToAWS:
    environment: 
      name: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v3
        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: sa-east-1
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

        - name: Setting stage and stack name
          run: |
              echo "STAGE=dev" 
              echo "PROJECT_NAME=Eureka2024" >> $GITHUB_ENV
              echo "STACK_NAME=${{ env.PROJECT_NAME }}Stack${{ env.STAGE }}" >> $GITHUB_ENV

        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
    
        - name: Installing Dependencies to Deploy
          run: |
            npm install -g aws-cdk
            cd iac
            pip install -r requirements.txt

        - name: Setup env
          run: |
            echo AWS_REGION=${{ vars.AWS_REGION }} >> $GITHUB_ENV
            echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
            echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
            

            echo ${{ env.AWS_REGION }}
            echo ${{ env.AWS_ACCOUNT_ID }}
            echo ${{ env.STACK_NAME }}
            echo ${{ env.GITHUB_REF_NAME }}

        - name: Deploy with CDK
          run: |
            cd iac
            cdk synth
            cdk deploy --require-approval never 
