name: Django CD  Test

on:
  push:
    branches:
      - prod
      - dev
      - homolog

jobs:
  DjangoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
