name: Django CI Test

on:
    workflow_call:
    workflow_dispatch:
    push:
    pull_request:

jobs:
  DjangoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Setup Docker
        run: |
            cd docker
            docker-compose up -d
      - name: Run tests
        run: |
            python manage.py test
